In [1]:
import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt # for making figures
%matplotlib inline

In [2]:
# read in all the words
words = open('names.txt', 'r').read().splitlines()
words[:8]

['emma', 'olivia', 'ava', 'isabella', 'sophia', 'charlotte', 'mia', 'amelia']

In [3]:
len(words)

32033

In [4]:
# build the vocabulary of characters and mappings to/from integers
chars = sorted(list(set(''.join(words))))
stoi = {s:i+1 for i,s in enumerate(chars)}
stoi['.'] = 0
itos = {i:s for s,i in stoi.items()}
print(itos)

{1: 'a', 2: 'b', 3: 'c', 4: 'd', 5: 'e', 6: 'f', 7: 'g', 8: 'h', 9: 'i', 10: 'j', 11: 'k', 12: 'l', 13: 'm', 14: 'n', 15: 'o', 16: 'p', 17: 'q', 18: 'r', 19: 's', 20: 't', 21: 'u', 22: 'v', 23: 'w', 24: 'x', 25: 'y', 26: 'z', 0: '.'}


In [7]:
# build the dataset

block_size = 3 # context length: how many characters do we take to predict the next one?
X, Y = [], []
for w in words[:5]:
  
  print(w)
  context = [0] * block_size
  for ch in w + '.':
    ix = stoi[ch]
    X.append(context)
    Y.append(ix)
    print(''.join(itos[i] for i in context), '--->', itos[ix])
    context = context[1:] + [ix] # crop and append
  
X = torch.tensor(X)
Y = torch.tensor(Y)

emma
... ---> e
..e ---> m
.em ---> m
emm ---> a
mma ---> .
olivia
... ---> o
..o ---> l
.ol ---> i
oli ---> v
liv ---> i
ivi ---> a
via ---> .
ava
... ---> a
..a ---> v
.av ---> a
ava ---> .
isabella
... ---> i
..i ---> s
.is ---> a
isa ---> b
sab ---> e
abe ---> l
bel ---> l
ell ---> a
lla ---> .
sophia
... ---> s
..s ---> o
.so ---> p
sop ---> h
oph ---> i
phi ---> a
hia ---> .


In [8]:
X.shape, X.dtype, Y.shape, Y.dtype

(torch.Size([32, 3]), torch.int64, torch.Size([32]), torch.int64)

In [9]:
X

tensor([[ 0,  0,  0],
        [ 0,  0,  5],
        [ 0,  5, 13],
        [ 5, 13, 13],
        [13, 13,  1],
        [ 0,  0,  0],
        [ 0,  0, 15],
        [ 0, 15, 12],
        [15, 12,  9],
        [12,  9, 22],
        [ 9, 22,  9],
        [22,  9,  1],
        [ 0,  0,  0],
        [ 0,  0,  1],
        [ 0,  1, 22],
        [ 1, 22,  1],
        [ 0,  0,  0],
        [ 0,  0,  9],
        [ 0,  9, 19],
        [ 9, 19,  1],
        [19,  1,  2],
        [ 1,  2,  5],
        [ 2,  5, 12],
        [ 5, 12, 12],
        [12, 12,  1],
        [ 0,  0,  0],
        [ 0,  0, 19],
        [ 0, 19, 15],
        [19, 15, 16],
        [15, 16,  8],
        [16,  8,  9],
        [ 8,  9,  1]])

In [10]:
Y

tensor([ 5, 13, 13,  1,  0, 15, 12,  9, 22,  9,  1,  0,  1, 22,  1,  0,  9, 19,
         1,  2,  5, 12, 12,  1,  0, 19, 15, 16,  8,  9,  1,  0])

In [14]:
C = torch.randn((27, 2))

In [18]:
C[5]

tensor([-0.7711, -1.1401])

In [27]:
C[X]

tensor([[[-0.1333, -2.0592],
         [-0.1333, -2.0592],
         [-0.1333, -2.0592]],

        [[-0.1333, -2.0592],
         [-0.1333, -2.0592],
         [-0.7711, -1.1401]],

        [[-0.1333, -2.0592],
         [-0.7711, -1.1401],
         [ 0.5486, -0.1139]],

        [[-0.7711, -1.1401],
         [ 0.5486, -0.1139],
         [ 0.5486, -0.1139]],

        [[ 0.5486, -0.1139],
         [ 0.5486, -0.1139],
         [-0.2342,  0.2694]],

        [[-0.1333, -2.0592],
         [-0.1333, -2.0592],
         [-0.1333, -2.0592]],

        [[-0.1333, -2.0592],
         [-0.1333, -2.0592],
         [-1.1741, -0.2508]],

        [[-0.1333, -2.0592],
         [-1.1741, -0.2508],
         [-1.2671, -1.4794]],

        [[-1.1741, -0.2508],
         [-1.2671, -1.4794],
         [-0.6388, -0.8402]],

        [[-1.2671, -1.4794],
         [-0.6388, -0.8402],
         [ 0.0245,  0.1532]],

        [[-0.6388, -0.8402],
         [ 0.0245,  0.1532],
         [-0.6388, -0.8402]],

        [[ 0.0245,  0

In [28]:
C[X].shape

torch.Size([32, 3, 2])

In [30]:
C[X].view([-1,6]).shape

torch.Size([32, 6])